// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sol_Demo.Infrastructure;

public partial class User
{
    public decimal Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }
}