// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Sol_Demo.Infrastructure;

public partial class UsersCommunication
{
    public decimal Id { get; set; }

    public string MobileNo { get; set; }

    public string EmailId { get; set; }
}